image: node:latest

stages:
  - build
  - test
  - flow
  - deploy
  - run

variables:
  repo: "easymech-frontend"

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

build:
  stage: build
  script:
    - pwd
    - ls
    - npm install
    - npm run build

test:
  stage: test
  script:
    - pwd
    - ls
    - npm install
    - npm test

flow:
  stage: flow
  script:
    - pwd
    - ls
    - npm install
    - npm run flow

deploy:
    stage: deploy
    environment: Staging
    only:
      - master
    script:
      - ls
      - pwd
      - cd ..
      - sshpass -V
      - export SSHPASS=$USER_PASS
      - sshpass -e ssh -o stricthostkeychecking=no gitlab@sinv-56057.edu.hsr.ch date
      - sshpass -e ssh -o stricthostkeychecking=no gitlab@sinv-56057.edu.hsr.ch "sudo /app/scripts/docker-cleanup.sh 40007 easymech-frontend"
      - sshpass -e scp -o stricthostkeychecking=no -r $repo/ gitlab@sinv-56057.edu.hsr.ch:/app/docker
      - sshpass -e ssh -o stricthostkeychecking=no gitlab@sinv-56057.edu.hsr.ch "sudo /app/scripts/docker-frontend.sh 40007 easymech-frontend"
